In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [2]:
DATA_PATH = "/Users/animeshdash/downloads/weatherHistory.csv"
df = pd.read_csv(DATA_PATH)
df

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [3]:
df.isna().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [4]:
print(df['Precip Type'].value_counts())
print(df['Summary'].value_counts())

Precip Type
rain    85224
snow    10712
Name: count, dtype: int64
Summary
Partly Cloudy                          31733
Mostly Cloudy                          28094
Overcast                               16597
Clear                                  10890
Foggy                                   7148
Breezy and Overcast                      528
Breezy and Mostly Cloudy                 516
Breezy and Partly Cloudy                 386
Dry and Partly Cloudy                     86
Windy and Partly Cloudy                   67
Light Rain                                63
Breezy                                    54
Windy and Overcast                        45
Humid and Mostly Cloudy                   40
Drizzle                                   39
Breezy and Foggy                          35
Windy and Mostly Cloudy                   35
Dry                                       34
Humid and Partly Cloudy                   17
Dry and Mostly Cloudy                     14
Rain                                      10
Windy                                      8
Humid and Overcast                         7
Windy and Foggy                            4
Dangerously Windy and Partly Cloudy        1
Windy and Dry                              1
Breezy and Dry                             1
Name: count, dtype: int64

In [5]:
df.dropna(inplace=True)

In [5]:
df = df.drop(columns= ["Formatted Date","Daily Summary","Summary","Apparent Temperature (C)"])
df

,Precip Type,Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
0,rain,9.472222,0.89,14.1197,251.0,15.8263,0.0,1015.13
1,rain,9.355556,0.86,14.2646,259.0,15.8263,0.0,1015.63
2,rain,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94
3,rain,8.288889,0.83,14.1036,269.0,15.8263,0.0,1016.41
4,rain,8.755556,0.83,11.0446,259.0,15.8263,0.0,1016.51
...,...,...,...,...,...,...,...,...
96448,rain,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36
96449,rain,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16
96450,rain,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66
96451,rain,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95
96452,rain,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16

In [6]:
df.describe()

,Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
count,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.0,96453.000000
mean,11.932678,0.734899,10.810640,187.509232,10.347325,0.0,1003.235956
std,9.551546,0.195473,6.913571,107.383428,4.192123,0.0,116.969906
min,-21.822222,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,4.688889,0.600000,5.828200,116.000000,8.339800,0.0,1011.900000
50%,12.000000,0.780000,9.965900,180.000000,10.046400,0.0,1016.450000
75%,18.838889,0.890000,14.135800,290.000000,14.812000,0.0,1021.090000
max,39.905556,1.000000,63.852600,359.000000,16.100000,0.0,1046.380000

In [7]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [8]:
print(X)
print(y)

      Precip Type  Temperature (C)  Humidity  Wind Speed (km/h)  \
0            rain         9.472222      0.89            14.1197
1            rain         9.355556      0.86            14.2646
2            rain         9.377778      0.89             3.9284
3            rain         8.288889      0.83            14.1036
4            rain         8.755556      0.83            11.0446
...           ...              ...       ...                ...
96448        rain        26.016667      0.43            10.9963
96449        rain        24.583333      0.48            10.0947
96450        rain        22.038889      0.56             8.9838
96451        rain        21.522222      0.60            10.5294
96452        rain        20.438889      0.61             5.8765

       Wind Bearing (degrees)  Visibility (km)  Loud Cover
0                       251.0          15.8263         0.0
1                       259.0          15.8263         0.0
2                       204.0          14.9569         0.0
3                       269.0          15.8263         0.0
4                       259.0          15.8263         0.0
...                       ...              ...         ...
96448                    31.0          16.1000         0.0
96449                    20.0          15.5526         0.0
96450                    30.0          16.1000         0.0
96451                    20.0          16.1000         0.0
96452                    39.0          15.5204         0.0

[96453 rows x 7 columns]
0        1015.13
1        1015.63
2        1015.94
3        1016.41
4        1016.51
          ...
96448    1014.36
96449    1015.16
96450    1015.66
96451    1015.95
96452    1016.16
Name: Pressure (millibars), Length: 96453, dtype: float64

In [9]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(sparse_output=False),[0,1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[  1.       0.       0.     ... 251.      15.8263   0.    ]
 [  1.       0.       0.     ... 259.      15.8263   0.    ]
 [  1.       0.       0.     ... 204.      14.9569   0.    ]
 ...
 [  1.       0.       0.     ...  30.      16.1      0.    ]
 [  1.       0.       0.     ...  20.      16.1      0.    ]
 [  1.       0.       0.     ...  39.      15.5204   0.    ]]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [12]:
print(X_train)

[[  1.       0.       0.     ... 340.      11.27     0.    ]
 [  1.       0.       0.     ... 165.      10.3523   0.    ]
 [  1.       0.       0.     ...   1.      16.1      0.    ]
 ...
 [  1.       0.       0.     ...  49.      11.27     0.    ]
 [  0.       1.       0.     ...  20.       0.3542   0.    ]
 [  1.       0.       0.     ... 354.      14.9086   0.    ]]

In [17]:
mm = MinMaxScaler()
X_train[:, 2:] = mm.fit_transform(X_train[:, 2:])
X_test[:, 2:] = mm.transform(X_test[:, 2:])